import * as productsControllers from "./productsControllers.js";
import * as usersControllers from "./usersControllers.js";
import * as sessionsControllers from "./sessionsControllers.js";
import * as cartsControllers from "./cartsControllers.js";
import * as viewsControllers from "./viewsControllers.js";
import * as ticketsControllers from "./ticketsControllers.js";
import * as evolutionControllers from "./evolutionControllers.js";
import * as socketControllers from "./socketControllers.js";
import * as chatControllers from "./chatControllers.js";
import * as evolutionApi from "./evolutionApiControllers.js";

export const products = productsControllers;
export const users = usersControllers;
export const sessions = sessionsControllers;
export const carts = cartsControllers;
export const views = viewsControllers;
export const tickets = ticketsControllers;
export const evolution = evolutionControllers;
export const socket = socketControllers;
export const chat = chatControllers;
export const evoApi = evolutionApi;
